
package tpo10.search;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonSearch", targetNamespace = "http://search.tpo10/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonSearch {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<tpo10.search.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchForPeople", targetNamespace = "http://search.tpo10/", className = "tpo10.search.SearchForPeople")
    @ResponseWrapper(localName = "searchForPeopleResponse", targetNamespace = "http://search.tpo10/", className = "tpo10.search.SearchForPeopleResponse")
    @Action(input = "http://search.tpo10/PersonSearch/searchForPeopleRequest", output = "http://search.tpo10/PersonSearch/searchForPeopleResponse")
    public List<Person> searchForPeople(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchQuery arg0);

}
